// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-k-LDk8nEEx4fRN7maREPVj1tpG25N68',
    appId: '1:1069841684665:web:ee135689e893be34a82368',
    messagingSenderId: '1069841684665',
    projectId: 'login-96502',
    authDomain: 'login-96502.firebaseapp.com',
    storageBucket: 'login-96502.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6STgBPe78arry1xBt_rprWoiuq38WDZs',
    appId: '1:1069841684665:android:0b819ef60625c73ea82368',
    messagingSenderId: '1069841684665',
    projectId: 'login-96502',
    storageBucket: 'login-96502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQT465rnZfsEtFfM8S1Uw3hweNPQbyvqY',
    appId: '1:1069841684665:ios:fbf37210c2d6e028a82368',
    messagingSenderId: '1069841684665',
    projectId: 'login-96502',
    storageBucket: 'login-96502.appspot.com',
    iosClientId: '1069841684665-9cj1ntlqc6kr4dr73nqc7fgmg53lpvk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.typingContestMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQT465rnZfsEtFfM8S1Uw3hweNPQbyvqY',
    appId: '1:1069841684665:ios:a7e0069ed73c6faaa82368',
    messagingSenderId: '1069841684665',
    projectId: 'login-96502',
    storageBucket: 'login-96502.appspot.com',
    iosClientId: '1069841684665-t85846roltasskpqrotemhjblm4ujiuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.typingContestMobile.RunnerTests',
  );
}
